services:
  borg:
    image: ghcr.io/anotherstranger/borg-server:latest
    container_name: borg_server
    restart: always
    environment:
      BORG_AUTHORIZED_KEYS: |
        # comment
        key_one
      BORG_SERVE_ADDITIONAL_ARGS: "--storage-quota 900G --append-only"
      BORG_UID: "1000"
      BORG_GID: "1000"
      ENSURE_BACKUP_PERMISSIONS: true
    volumes:
      - backup:/home/borg/backups
      - server_keys:/var/lib/docker-borg
    ports:
      - "8022:22"
volumes:
  backup:
  server_keys: